### ISSUE TITLE
Bazel LLVM toolchain 10.0.0 causes known issue

### ISSUE THREAD

**Issue by xrendan** [google/fully-homomorphic-encryption#16]
On arch, the Bazel toolchain causes an unknown platform error (which seems to be noted but not fixed). Is there a reason that LLVM is pinned to 10.0.0 instead of 10.0.1? This just seems like a roadblock for developers to experiment with the library

From the bazel WORKSPACE file:
```
llvm_toolchain(
    name = "llvm_toolchain",
    # Try using llvm version 10.0.1 if you are getting an "Unknown LLVM
    # release" error.  This is a known issue for Ubuntu 16.04 LTS.
    llvm_version = "10.0.0",
)
```

**Comment by xrendan** [comment]
Actually, the compilation with 10.0.1 failed too, it's likely easier to just use the docker build on Arch.

**Comment by j2kun** [comment]
Hi Brendan,

We don't have specific plans to support Arch officially at this time. We have been discussing internally the possibility of setting up a suite of Dockerfiles for different architectures and compiler versions (e.g., gcc12 has been causing recent issues).

The priority on this is low, due to the experimental nature of this repository, but we have it on an internal backlog.

Please do update this issue with any resolution you find that makes compilation work on Arch. In the mean time, I'll close this issue.
